### ISSUE TITLE
Please add Windows patch and test from conda-forge

### ISSUE THREAD

**Issue by ccordoba12** [AnacondaRecipes/pydot-feedstock#1]
Pinging @jjhelmus and @nehaljwani about this one.

This PR https://github.com/conda-forge/pydot-feedstock/pull/2 fixed Pydot on Windows for good. However, its changes haven't been picked up by defaults and hence people is still posting ugly solutions to workaround Pydot's breakage:

https://stackoverflow.com/a/53560595/438386

So could you include those changes and release a new build? Thanks for your help!

**Comment by jjhelmus** [comment]
Done, build 1 has the linked changes.
